/*
 Hyphenator 3.3.0 - client side hyphenation for webbrowsers
 Copyright (C) 2011  Mathias Nater, Zürich (mathias at mnn dot ch)
 Project and Source hosted on http://code.google.com/p/hyphenator/

 This JavaScript code is free software: you can redistribute
 it and/or modify it under the terms of the GNU Lesser
 General Public License (GNU LGPL) as published by the Free Software
 Foundation, either version 3 of the License, or (at your option)
 any later version.  The code is distributed WITHOUT ANY WARRANTY;
 without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the GNU GPL for more details.

 As additional permission under GNU GPL version 3 section 7, you
 may distribute non-source (e.g., minimized or compacted) forms of
 that code without the copy of the GNU GPL normally required by
 section 4, provided you include this license notice and a URL
 through which recipients can access the Corresponding Source.
*/
var Hyphenator=function(f){var p={be:"be.js",ca:"ca.js",cs:"cs.js",da:"da.js",bn:"bn.js",de:"de.js",el:"el-monoton.js","el-monoton":"el-monoton.js","el-polyton":"el-polyton.js",en:"en-us.js","en-gb":"en-gb.js","en-us":"en-us.js",es:"es.js",fi:"fi.js",fr:"fr.js",grc:"grc.js",gu:"gu.js",hi:"hi.js",hu:"hu.js",hy:"hy.js",it:"it.js",kn:"kn.js",la:"la.js",lt:"lt.js",lv:"lv.js",ml:"ml.js",no:"no-nb.js","no-nb":"no-nb.js",nl:"nl.js",or:"or.js",pa:"pa.js",pl:"pl.js",pt:"pt.js",ru:"ru.js",sl:"sl.js",sv:"sv.js",
ta:"ta.js",te:"te.js",tr:"tr.js",uk:"uk.js"},ea=function(){var a,b="";for(a in p)p.hasOwnProperty(a)&&(b+=a+", ");return b=b.substring(0,b.length-2)}(),H={be:"\u041c\u043e\u0432\u0430 \u0433\u044d\u0442\u0430\u0433\u0430 \u0441\u0430\u0439\u0442\u0430 \u043d\u0435 \u043c\u043e\u0436\u0430 \u0431\u044b\u0446\u044c \u0432\u044b\u0437\u043d\u0430\u0447\u0430\u043d\u044b \u0430\u045e\u0442\u0430\u043c\u0430\u0442\u044b\u0447\u043d\u0430. \u041a\u0430\u043b\u0456 \u043b\u0430\u0441\u043a\u0430 \u043f\u0430\u043a\u0430\u0436\u044b\u0446\u0435 \u043c\u043e\u0432\u0443:",
cs:"Jazyk t\u00e9to internetov\u00e9 str\u00e1nky nebyl automaticky rozpozn\u00e1n. Ur\u010dete pros\u00edm jej\u00ed jazyk:",da:"Denne websides sprog kunne ikke bestemmes. Angiv venligst sprog:",de:"Die Sprache dieser Webseite konnte nicht automatisch bestimmt werden. Bitte Sprache angeben:",en:"The language of this website could not be determined automatically. Please indicate the main language:",es:"El idioma del sitio no pudo determinarse autom%E1ticamente. Por favor, indique el idioma principal:",
fi:"Sivun kielt%E4 ei tunnistettu automaattisesti. M%E4%E4rit%E4 sivun p%E4%E4kieli:",fr:"La langue de ce site n%u2019a pas pu %EAtre d%E9termin%E9e automatiquement. Veuillez indiquer une langue, s.v.p.%A0:",hu:"A weboldal nyelv\u00e9t nem siker\u00fclt automatikusan meg\u00e1llap\u00edtani. K\u00e9rem adja meg a nyelvet:",hy:"\u0549\u0570\u0561\u057b\u0578\u0572\u057e\u0565\u0581 \u0570\u0561\u0575\u057f\u0576\u0561\u0562\u0565\u0580\u0565\u056c \u0561\u0575\u057d \u056f\u0561\u0575\u0584\u056b \u056c\u0565\u0566\u0578\u0582\u0576\u0589 \u053d\u0576\u0564\u0580\u0578\u0582\u0574 \u0565\u0576\u0584 \u0576\u0577\u0565\u0584 \u0570\u056b\u0574\u0576\u0561\u056f\u0561\u0576 \u056c\u0565\u0566\u0578\u0582\u0576\u055d",
it:"Lingua del sito sconosciuta. Indicare una lingua, per favore:",kn:"\u0c9c\u0cbe\u0cb2 \u0ca4\u0cbe\u0ca3\u0ca6 \u0cad\u0cbe\u0cb7\u0cc6\u0caf\u0ca8\u0ccd\u0ca8\u0cc1 \u0ca8\u0cbf\u0cb0\u0ccd\u0ca7\u0cb0\u0cbf\u0cb8\u0cb2\u0cc1 \u0cb8\u0cbe\u0ca7\u0ccd\u0caf\u0cb5\u0cbe\u0c97\u0cc1\u0ca4\u0ccd\u0ca4\u0cbf\u0cb2\u0ccd\u0cb2. \u0ca6\u0caf\u0cb5\u0cbf\u0c9f\u0ccd\u0c9f\u0cc1 \u0cae\u0cc1\u0c96\u0ccd\u0caf \u0cad\u0cbe\u0cb7\u0cc6\u0caf\u0ca8\u0ccd\u0ca8\u0cc1 \u0cb8\u0cc2\u0c9a\u0cbf\u0cb8\u0cbf:",
lt:"Nepavyko automati\u0161kai nustatyti \u0161ios svetain\u0117s kalbos. Pra\u0161ome \u012fvesti kalb\u0105:",lv:"\u0160\u012bs lapas valodu nevar\u0113ja noteikt autom\u0101tiski. L\u016bdzu nor\u0101diet pamata valodu:",ml:"\u0d08 \u0d35\u0d46%u0D2C%u0D4D%u200C\u0d38\u0d48\u0d31\u0d4d\u0d31\u0d3f\u0d28\u0d4d\u0d31\u0d46 \u0d2d\u0d3e\u0d37 \u0d15\u0d23\u0d4d\u0d1f\u0d41\u0d2a\u0d3f\u0d1f\u0d3f\u0d2f\u0d4d\u0d15\u0d4d\u0d15\u0d3e%u0D28%u0D4D%u200D \u0d15\u0d34\u0d3f\u0d1e\u0d4d\u0d1e\u0d3f\u0d32\u0d4d\u0d32. \u0d2d\u0d3e\u0d37 \u0d0f\u0d24\u0d3e\u0d23\u0d46\u0d28\u0d4d\u0d28\u0d41 \u0d24\u0d3f\u0d30\u0d1e\u0d4d\u0d1e\u0d46\u0d1f\u0d41\u0d15\u0d4d\u0d15\u0d41\u0d15:",
nl:"De taal van deze website kan niet automatisch worden bepaald. Geef de hoofdtaal op:",no:"Nettstedets spr\u00e5k kunne ikke finnes automatisk. Vennligst oppgi spr\u00e5k:",pt:"A l\u00edngua deste site n\u00e3o p\u00f4de ser determinada automaticamente. Por favor indique a l\u00edngua principal:",ru:"\u042f\u0437\u044b\u043a \u044d\u0442\u043e\u0433\u043e \u0441\u0430\u0439\u0442\u0430 \u043d\u0435 \u043c\u043e\u0436\u0435\u0442 \u0431\u044b\u0442\u044c \u043e\u043f\u0440\u0435\u0434\u0435\u043b\u0435\u043d \u0430\u0432\u0442\u043e\u043c\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u0438. \u041f\u043e\u0436\u0430\u043b\u0443\u0439\u0441\u0442\u0430 \u0443\u043a\u0430\u0436\u0438\u0442\u0435 \u044f\u0437\u044b\u043a:",
sl:"Jezika te spletne strani ni bilo mogo\u010de samodejno dolo\u010diti. Prosim navedite jezik:",sv:"Spr%E5ket p%E5 den h%E4r webbplatsen kunde inte avg%F6ras automatiskt. V%E4nligen ange:",tr:"Bu web sitesinin dili otomatik olarak tespit edilememi\u015ftir. L\u00fctfen d\u00f6k\u00fcman\u0131n dilini se\u00e7iniz%A0:",uk:"\u041c\u043e\u0432\u0430 \u0446\u044c\u043e\u0433\u043e \u0432\u0435\u0431-\u0441\u0430\u0439\u0442\u0443 \u043d\u0435 \u043c\u043e\u0436\u0435 \u0431\u0443\u0442\u0438 \u0432\u0438\u0437\u043d\u0430\u0447\u0435\u043d\u0430 \u0430\u0432\u0442\u043e\u043c\u0430\u0442\u0438\u0447\u043d\u043e. \u0411\u0443\u0434\u044c \u043b\u0430\u0441\u043a\u0430, \u0432\u043a\u0430\u0436\u0456\u0442\u044c \u0433\u043e\u043b\u043e\u0432\u043d\u0443 \u043c\u043e\u0432\u0443:"},
X=function(){for(var a=document.getElementsByTagName("script"),b=0,c,d;c=a[b++];)if(c.src&&(d=c.src,c=d.indexOf("Hyphenator.js"),c!==-1))return d.substring(0,c);return"http://hyphenator.googlecode.com/svn/trunk/"}(),fa=function(){var a=!1;f.location.href.indexOf(X)!==-1&&(a=!0);return a}(),x=!1,s=0,I=!1,k=f,t=!1,Y={script:!0,code:!0,pre:!0,img:!0,br:!0,samp:!0,kbd:!0,"var":!0,abbr:!0,acronym:!0,sub:!0,sup:!0,button:!0,option:!0,label:!0,textarea:!0,input:!0},y=!0,z="local",l,J=!1,K=!0,L=!1,C="hyphenate",
A="donthyphenate",q=6,B=1,v=function(){var a=null,b=!1,c=document.getElementsByTagName("script"),d,e;d=0;for(e=c.length;d<e;d++)c[d].getAttribute("src")&&(a=c[d].getAttribute("src")),a&&a.indexOf("Hyphenator.js?bm=true")!==-1&&(b=!0);return b}(),i=null,D="",w=[],h={},ga=function(a){var b,c=0;for(b in a)a.hasOwnProperty(b)&&c++;return c},m={},Z=RegExp("((\\w*://)?((\\w*:)?(\\w*)@)?((([\\d]{1,3}\\.){3}([\\d]{1,3}))|((www\\.|[a-zA-Z]\\.)?[a-zA-Z0-9\\-\\.]+\\.([a-z]{2,4})))(:\\d*)?(/[\\w#!:\\.?\\+=&%@!\\-]*)*)|([\\w-\\.]+@[\\w\\.]+)",
"i"),M=function(){var a,b=navigator.userAgent.toLowerCase();a=String.fromCharCode(8203);b.indexOf("msie 6")!==-1&&(a="");b.indexOf("opera")!==-1&&b.indexOf("version/10.00")!==-1&&(a="");return a}(),N=function(a,b){b=b||k;if(document.createElementNS)return b.document.createElementNS("http://www.w3.org/1999/xhtml",a);else if(document.createElement)return b.document.createElement(a)},O=function(){},r=function(a){f.alert("Hyphenator.js says:\n\nAn Error ocurred:\n"+a.message)},P=function(){var a,b=[],
c,d;if(document.getElementsByClassName)b=k.document.getElementsByClassName(C);else{a=k.document.getElementsByTagName("*");d=a.length;for(c=0;c<d;c++)a[c].className.indexOf(C)!==-1&&a[c].className.indexOf(A)===-1&&b.push(a[c])}return b},E="hidden",u=String.fromCharCode(173),Q=M,R=!0,S=function(){var a={},b="HyphenatorExpando_"+Math.random(),c=0;return{getDataForElem:function(c){return a[c[b].id]},setDataForElem:function(d,e){var j;d[b]&&d[b].id!==""?j=d[b].id:(j=c++,d[b]={id:j});a[j]=e},appendDataForElem:function(c,
e){for(var j in e)e.hasOwnProperty(j)&&(a[c[b].id][j]=e[j])},delDataOfElem:function(c){delete a[c[b]]}}}(),ha=function(a,b){function c(a){k=a||f;if(!n[k.location.href]&&(!x||k!=f.parent))x=!0,b(),n[k.location.href]=!0}function d(){try{document.documentElement.doScroll("left")}catch(a){setTimeout(d,1);return}c(f)}function e(){var a,d,e=f.frames.length;if(t&&e>0){for(a=0;a<e;a++){d=void 0;try{d=f.frames[a].document.toString()}catch(j){d=void 0}d&&c(f.frames[a])}k=f;b();n[f.location.href]=!0}else c(f)}
var j=function(){},g,n={};if(x&&!n[a.location.href])b(),n[a.location.href]=!0;else if(document.addEventListener?j=function(){document.removeEventListener("DOMContentLoaded",j,!1);t&&f.frames.length>0||c(f)}:document.attachEvent&&(j=function(){document.readyState==="complete"&&(document.detachEvent("onreadystatechange",j),t&&f.frames.length>0||c(f))}),document.addEventListener)document.addEventListener("DOMContentLoaded",j,!1),f.addEventListener("load",e,!1);else if(document.attachEvent){document.attachEvent("onreadystatechange",
j);f.attachEvent("onload",e);g=!1;try{g=f.frameElement===null}catch(o){}document.documentElement.doScroll&&g&&d()}},T=function(a,b){if(a.getAttribute("lang"))return a.getAttribute("lang").toLowerCase();try{if(a.getAttribute("xml:lang"))return a.getAttribute("xml:lang").toLowerCase()}catch(c){}if(a.tagName!=="HTML")return T(a.parentNode,!0);if(b)return i;return null},$=function(a){var a=a||k,b=a.document.getElementsByTagName("html")[0],a=a.document.getElementsByTagName("meta");i=T(b,!1);if(!i)for(b=
0;b<a.length;b++)a[b].getAttribute("http-equiv")&&a[b].getAttribute("http-equiv").toLowerCase()==="content-language"&&(i=a[b].getAttribute("content").toLowerCase()),a[b].getAttribute("name")&&a[b].getAttribute("name").toLowerCase()==="dc.language"&&(i=a[b].getAttribute("content").toLowerCase()),a[b].getAttribute("name")&&a[b].getAttribute("name").toLowerCase()==="language"&&(i=a[b].getAttribute("content").toLowerCase());!i&&t&&k!=f.parent&&$(f.parent);!i&&D!==""&&(i=D);i||(a=navigator.language?navigator.language:
navigator.userLanguage,a=a.substring(0,2),b=H.hasOwnProperty(a)?H[a]:H.en,b+=" (ISO 639-1)\n\n"+ea,i=f.prompt(unescape(b),a).toLowerCase());if(!p.hasOwnProperty(i))if(p.hasOwnProperty(i.split("-")[0]))i=i.split("-")[0];else throw b=Error('The language "'+i+'" is not yet supported.'),b;},ia=function(){var a,b,c=0,d=function(b,c,g){var f=0,o={};if(c&&E==="hidden")o.hasOwnStyle=b.getAttribute("style")?!0:!1,o.isHidden=!0,b.style.visibility="hidden";o.language=b.lang&&typeof b.lang==="string"?b.lang.toLowerCase():
g?g.toLowerCase():T(b,!0);g=o.language;p[g]?m[g]=!0:p.hasOwnProperty(g.split("-")[0])?(g=g.split("-")[0],o.language=g):v||r(Error("Language "+g+" is not yet supported."));S.setDataForElem(b,o);for(w.push(b);c=b.childNodes[f++];)c.nodeType===1&&!Y[c.nodeName.toLowerCase()]&&c.className.indexOf(A)===-1&&!(c in a)&&d(c,!1,g)};if(v)a=k.document.getElementsByTagName("body")[0],d(a,!1,i);else for(a=P();b=a[c++];)d(b,!0,"");Hyphenator.languages.hasOwnProperty(i)?Hyphenator.languages[i].prepared||(m[i]=!0):
m[i]=!0;w.length>0&&S.appendDataForElem(w[w.length-1],{isLast:!0})},U=function(a){var a=a.split(", "),b={},c,d,e;c=0;for(d=a.length;c<d;c++)e=a[c].replace(/-/g,""),b.hasOwnProperty(e)||(b[e]=a[c]);return b},ja=function(a){var b,c;if(p[a]&&!Hyphenator.languages[a]){b=X+"patterns/"+p[a];if(fa&&!v){c=null;typeof XMLHttpRequest!=="undefined"&&(c=new XMLHttpRequest);if(!c)try{c=new ActiveXObject("Msxml2.XMLHTTP")}catch(d){c=null}if(c&&(c.open("HEAD",b,!1),c.setRequestHeader("Cache-Control","no-cache"),
c.send(null),c.status===404)){r(Error("Could not load\n"+b));delete m[a];return}}if(N)a=f.document.getElementsByTagName("head").item(0),c=N("script",f),c.src=b,c.type="text/javascript",a.appendChild(c)}},V=function(a){var b=Hyphenator.languages[a],c;if(!b.prepared){if(y)b.cache={},b.cache=b.cache;if(J)b.redPatSet={};b.hasOwnProperty("exceptions")&&(Hyphenator.addExceptions(a,b.exceptions),delete b.exceptions);if(h.hasOwnProperty("global"))h.hasOwnProperty(a)?h[a]+=", "+h.global:h[a]=h.global;h.hasOwnProperty(a)?
(b.exceptions=U(h[a]),delete h[a]):b.exceptions={};var d,e,j,g,n={};j=Hyphenator.languages[a].patterns;for(c in j)if(j.hasOwnProperty(c)){c=parseInt(c,10);d=0;for(e=c;d=j[c].substring(d,e);)g=d.replace(/\d/g,""),n[g]=d,d=e,e+=c}Hyphenator.languages[a].patterns=n;Hyphenator.languages[a].patternsConverted=!0;c="[\\w"+b.specialChars+"@"+String.fromCharCode(173)+String.fromCharCode(8204)+"-]{"+q+",}";b.genRegExp=RegExp("((\\w*://)?((\\w*:)?(\\w*)@)?((([\\d]{1,3}\\.){3}([\\d]{1,3}))|((www\\.|[a-zA-Z]\\.)?[a-zA-Z0-9\\-\\.]+\\.([a-z]{2,4})))(:\\d*)?(/[\\w#!:\\.?\\+=&%@!\\-]*)*)|([\\w-\\.]+@[\\w\\.]+)|("+
c+")","gi");b.prepared=!0}if(l)try{l.setItem("Hyphenator_"+a,f.JSON.stringify(b))}catch(o){}},ka=function(a){var b,c,d,e;if(K){for(b in m)if(m.hasOwnProperty(b))if(l&&l.getItem("Hyphenator_"+b)){Hyphenator.languages[b]=f.JSON.parse(l.getItem("Hyphenator_"+b));if(h.hasOwnProperty("global"))for(e in d=U(h.global),d)d.hasOwnProperty(e)&&(Hyphenator.languages[b].exceptions[e]=d[e]);if(h.hasOwnProperty(b)){d=U(h[b]);for(e in d)d.hasOwnProperty(e)&&(Hyphenator.languages[b].exceptions[e]=d[e]);delete h[b]}d=
"[\\w"+Hyphenator.languages[b].specialChars+"@"+String.fromCharCode(173)+String.fromCharCode(8204)+"-]{"+q+",}";Hyphenator.languages[b].genRegExp=RegExp("((\\w*://)?((\\w*:)?(\\w*)@)?((([\\d]{1,3}\\.){3}([\\d]{1,3}))|((www\\.|[a-zA-Z]\\.)?[a-zA-Z0-9\\-\\.]+\\.([a-z]{2,4})))(:\\d*)?(/[\\w#!:\\.?\\+=&%@!\\-]*)*)|([\\w-\\.]+@[\\w\\.]+)|("+d+")","gi");delete m[b]}else ja(b);ga(m)===0?a():c=f.setInterval(function(){var b=!0,d;for(d in m)m.hasOwnProperty(d)&&(b=!1,Hyphenator.languages[d]&&(delete m[d],
V(d)));b&&(f.clearInterval(c),a())},100)}else{for(b in Hyphenator.languages)Hyphenator.languages.hasOwnProperty(b)&&V(b);a()}},F=function(){var a,b,c,d,e;d=Hyphenator.doHyphenation?"Hy-phen-a-tion":"Hyphenation";(a=k.document.getElementById("HyphenatorToggleBox"))?a.firstChild.data=d:(b=k.document.getElementsByTagName("body")[0],a=N("div",k),c=k.document.createAttribute("id"),c.nodeValue="HyphenatorToggleBox",e=k.document.createAttribute("class"),e.nodeValue=A,d=k.document.createTextNode(d),a.appendChild(d),
a.setAttributeNode(c),a.setAttributeNode(e),a.onclick=Hyphenator.toggleHyphenation,a.style.position="absolute",a.style.top="0px",a.style.right="0px",a.style.margin="0",a.style.backgroundColor="#AAAAAA",a.style.color="#FFFFFF",a.style.font="6pt Arial",a.style.letterSpacing="0.2em",a.style.padding="3px",a.style.cursor="pointer",a.style.WebkitBorderBottomLeftRadius="4px",a.style.MozBorderRadiusBottomleft="4px",b.appendChild(a))},W=function(a,b){var c=Hyphenator.languages[a],d,e,f,g,n,o,k,i,h=!1,l,m,
p,r,t,s,q=[];if(b==="")return"";if(b.indexOf(u)!==-1)return b;if(y&&c.cache.hasOwnProperty(b))return c.cache[b];if(c.exceptions.hasOwnProperty(b))return c.exceptions[b].replace(/-/g,u);if(b.indexOf("-")!==-1){d=b.split("-");e=0;for(f=d.length;e<f;e++)d[e]=W(a,d[e]);return d.join("-")}g="_"+b+"_";if(b.indexOf(String.fromCharCode(8204))!==-1){d=g.split(String.fromCharCode(8204));g=d.join("");e=0;for(f=d.length;e<f;e++)d[e]=d[e].length.toString();d.pop();q=d}d=g.length;f=g.split("");if(c.charSubstitution)for(n in c.charSubstitution)c.charSubstitution.hasOwnProperty(n)&&
(g=g.replace(RegExp(n,"g"),c.charSubstitution[n]));g=b.indexOf("'")!==-1?g.toLowerCase().replace("'","\u2019"):g.toLowerCase();n=[];t={0:0,1:1,2:2,3:3,4:4,5:5,6:6,7:7,8:8,9:9};r=d-c.shortestPattern;for(o=0;o<=r;o++){k=Math.min(d-o,c.longestPattern);for(i=c.shortestPattern;i<=k;i++)if(c.patterns.hasOwnProperty(l=g.substring(o,o+i))){h=c.patterns[l];J&&typeof h==="string"&&(c.redPatSet[l]=h);if(typeof h==="string"){p=0;s=[];for(e=0;e<h.length;e++)if(m=t[h.charAt(e)])s.push(e-p,m),p++;h=c.patterns[l]=
s}for(e=0;e<h.length;e++){m=o-1+h[e];if(!n[m]||n[m]<h[e+1])n[m]=h[e+1];e++}}}g=0;for(e=c.leftmin;e<=d-2-c.rightmin;e++)q.length>0&&q[0]===e&&(q.shift(),f.splice(e+g-1,0,String.fromCharCode(8204)),g++),n[e]&1&&(f.splice(e+g+1,0,u),g++);e=f.slice(1,-1).join("");y&&(c.cache[b]=e);return e},aa=function(a){return a.replace(/([:\/\.\?#&_,;!@]+)/gi,"$&"+Q)},G=function(a){var b,c=0,d;switch(u){case "|":b="\\|";break;case "+":b="\\+";break;case "*":b="\\*";break;default:b=u}for(;d=a.childNodes[c++];)d.nodeType===
3?(d.data=d.data.replace(RegExp(b,"g"),""),d.data=d.data.replace(RegExp(M,"g"),"")):d.nodeType===1&&G(d)},la=function(a){var b=a.ownerDocument.getElementsByTagName("body")[0],c,d,e,j,g,h=function(a){var a=a||f.event,a=a.target||a.srcElement,b=a.ownerDocument,h=b.getElementsByTagName("body")[0],i="defaultView"in b?b.defaultView:b.parentWindow;if(!a.tagName||!Y[a.tagName.toLowerCase()])c=b.createElement("div"),c.style.overflow="hidden",c.style.position="absolute",c.style.top="-5000px",c.style.height=
"1px",h.appendChild(c),f.getSelection?(d=i.getSelection(),e=d.getRangeAt(0),c.appendChild(e.cloneContents()),G(c),d.selectAllChildren(c),g=function(){c.parentNode.removeChild(c);d.addRange(e)}):(d=i.document.selection,e=d.createRange(),c.innerHTML=e.htmlText,G(c),j=h.createTextRange(),j.moveToElementText(c),j.select(),g=function(){c.parentNode.removeChild(c);e.text!==""&&e.select()}),f.setTimeout(g,0)};b&&(a=a||b,f.addEventListener?a.addEventListener("copy",h,!1):a.attachEvent("oncopy",h))},ma=function(a){var b=
S.getDataForElem(a),c=b.language,d,e,f,g=function(a){var b,c;switch(u){case "|":b="\\|";break;case "+":b="\\+";break;case "*":b="\\*";break;default:b=u}B>=2&&(c=a.split(" "),c[1]=c[1].replace(RegExp(b,"g"),""),c[1]=c[1].replace(RegExp(M,"g"),""),c=c.join(" "));B===3&&(c=c.replace(/[ ]+/g,String.fromCharCode(160)));return c};if(Hyphenator.languages.hasOwnProperty(c)){d=function(a){return Hyphenator.doHyphenation?Z.test(a)?aa(a):W(c,a):a};R&&a.tagName.toLowerCase()!=="body"&&la(a);for(f=0;e=a.childNodes[f++];)if(e.nodeType===
3&&e.data.length>=q&&(e.data=e.data.replace(Hyphenator.languages[c].genRegExp,d),B!==1))e.data=e.data.replace(/[\S]+ [\S]+$/,g)}if(b.isHidden&&E==="hidden")a.style.visibility="visible",b.hasOwnStyle?a.style.removeProperty?a.style.removeProperty("visibility"):a.style.removeAttribute&&a.style.removeAttribute("visibility"):(a.setAttribute("style",""),a.removeAttribute("style"));b.isLast&&(s--,s>-1E3&&s<=0&&(s=-2E3,O()))},ba=function(){function a(a,b){return function(){return a(b)}}for(var b=0,c;c=w[b++];)c.ownerDocument.location.href===
k.location.href&&f.setTimeout(a(ma,c),0)},ca=function(){try{if(z!=="none"&&typeof f.localStorage!=="undefined"&&typeof f.sessionStorage!=="undefined"&&typeof f.JSON.stringify!=="undefined"&&typeof f.JSON.parse!=="undefined")switch(z){case "session":l=f.sessionStorage;break;case "local":l=f.localStorage;break;default:l=void 0}}catch(a){}},da=function(){l&&l.setItem("Hyphenator_config",f.JSON.stringify({STORED:!0,classname:C,donthyphenateclassname:A,minwordlength:q,hyphenchar:u,urlhyphenchar:Q,togglebox:F,
displaytogglebox:L,remoteloading:K,enablecache:y,onhyphenationdonecallback:O,onerrorhandler:r,intermediatestate:E,selectorfunction:P,safecopy:R,doframes:t,storagetype:z,orphancontrol:B,dohyphenation:Hyphenator.doHyphenation,persistentconfig:I,defaultlanguage:D}))},na=function(){var a;l.getItem("Hyphenator_config")&&(a=f.JSON.parse(l.getItem("Hyphenator_config")),Hyphenator.config(a))};return{version:"3.3.0",doHyphenation:!0,languages:{},config:function(a){var b=function(b,c){return typeof a[b]===
c?!0:(r(Error("Config onError: "+b+" must be of type "+c)),!1)},c;if(a.hasOwnProperty("storagetype")){if(b("storagetype","string"))z=a.storagetype;l||ca()}!a.hasOwnProperty("STORED")&&l&&a.hasOwnProperty("persistentconfig")&&a.persistentconfig===!0&&na();for(c in a)if(a.hasOwnProperty(c))switch(c){case "STORED":break;case "classname":b("classname","string")&&(C=a[c]);break;case "donthyphenateclassname":b("donthyphenateclassname","string")&&(A=a[c]);break;case "minwordlength":b("minwordlength","number")&&
(q=a[c]);break;case "hyphenchar":if(b("hyphenchar","string")){if(a.hyphenchar==="&shy;")a.hyphenchar=String.fromCharCode(173);u=a[c]}break;case "urlhyphenchar":a.hasOwnProperty("urlhyphenchar")&&b("urlhyphenchar","string")&&(Q=a[c]);break;case "togglebox":b("togglebox","function")&&(F=a[c]);break;case "displaytogglebox":b("displaytogglebox","boolean")&&(L=a[c]);break;case "remoteloading":b("remoteloading","boolean")&&(K=a[c]);break;case "enablecache":b("enablecache","boolean")&&(y=a[c]);break;case "enablereducedpatternset":b("enablereducedpatternset",
"boolean")&&(J=a[c]);break;case "onhyphenationdonecallback":b("onhyphenationdonecallback","function")&&(O=a[c]);break;case "onerrorhandler":b("onerrorhandler","function")&&(r=a[c]);break;case "intermediatestate":b("intermediatestate","string")&&(E=a[c]);break;case "selectorfunction":b("selectorfunction","function")&&(P=a[c]);break;case "safecopy":b("safecopy","boolean")&&(R=a[c]);break;case "doframes":b("doframes","boolean")&&(t=a[c]);break;case "storagetype":b("storagetype","string")&&(z=a[c]);break;
case "orphancontrol":b("orphancontrol","number")&&(B=a[c]);break;case "dohyphenation":if(b("dohyphenation","boolean"))Hyphenator.doHyphenation=a[c];break;case "persistentconfig":b("persistentconfig","boolean")&&(I=a[c]);break;case "defaultlanguage":b("defaultlanguage","string")&&(D=a[c]);break;default:r(Error("Hyphenator.config: property "+c+" not known."))}l&&I&&da()},run:function(){s=0;var a=function(){try{k.document.getElementsByTagName("frameset").length>0||(s++,$(void 0),ia(),ka(ba),L&&F())}catch(a){r(a)}},
b,c,d=f.frames.length;l||ca();!x&&!v&&ha(f,a);if(v||x){if(t&&d>0)for(b=0;b<d;b++){c=void 0;try{c=f.frames[b].document.toString()}catch(e){c=void 0}c&&(k=f.frames[b],a())}k=f;a()}},addExceptions:function(a,b){a===""&&(a="global");h.hasOwnProperty(a)?h[a]+=", "+b:h[a]=b},hyphenate:function(a,b){var c,d,e;if(Hyphenator.languages.hasOwnProperty(b))if(Hyphenator.languages[b].prepared||V(b),c=function(a){return Z.test(a)?aa(a):W(b,a)},typeof a==="string"||a.constructor===String)return a.replace(Hyphenator.languages[b].genRegExp,
c);else{if(typeof a==="object")for(e=0;d=a.childNodes[e++];)d.nodeType===3&&d.data.length>=q?d.data=d.data.replace(Hyphenator.languages[b].genRegExp,c):d.nodeType===1&&(d.lang!==""?Hyphenator.hyphenate(d,d.lang):Hyphenator.hyphenate(d,b))}else r(Error('Language "'+b+'" is not loaded.'))},getRedPatternSet:function(a){return Hyphenator.languages[a].redPatSet},isBookmarklet:function(){return v},getConfigFromURI:function(){var a=null,b={},c=document.getElementsByTagName("script"),d,e,f;d=0;for(e=c.length;d<
e;d++)if(c[d].getAttribute("src")&&(a=c[d].getAttribute("src")),a&&(f=a.indexOf("Hyphenator.js?"),f!==-1)){c=a.substring(f+14).split("&");for(a=0;a<c.length;a++)d=c[a].split("="),d[0]!=="bm"&&(b[d[0]]=d[1]==="true"?!0:d[1]==="false"?!1:isFinite(d[1])?parseInt(d[1],10):d[0]==="onhyphenationdonecallback"?new Function("",d[1]):d[1]);break}return b},toggleHyphenation:function(){if(Hyphenator.doHyphenation){for(var a=0,b;b=w[a++];)G(b);Hyphenator.doHyphenation=!1}else ba(),Hyphenator.doHyphenation=!0;
da();F()}}}(window);Hyphenator.languages=Hyphenator.languages;Hyphenator.config=Hyphenator.config;Hyphenator.run=Hyphenator.run;Hyphenator.addExceptions=Hyphenator.addExceptions;Hyphenator.hyphenate=Hyphenator.hyphenate;Hyphenator.getRedPatternSet=Hyphenator.getRedPatternSet;Hyphenator.isBookmarklet=Hyphenator.isBookmarklet;Hyphenator.getConfigFromURI=Hyphenator.getConfigFromURI;Hyphenator.toggleHyphenation=Hyphenator.toggleHyphenation;window.Hyphenator=Hyphenator;
Hyphenator.isBookmarklet()&&(Hyphenator.config({displaytogglebox:!0,intermediatestate:"visible",doframes:!0}),Hyphenator.config(Hyphenator.getConfigFromURI()),Hyphenator.run());
